ALTER TABLE recipe
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;

UPDATE recipe
SET updated_at = CURRENT_TIMESTAMP
WHERE updated_at IS NULL;

ALTER TABLE recipe
ALTER COLUMN updated_at SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE recipe
ALTER COLUMN updated_at SET NOT NULL;
